name: Deploy Docker HUB

on:
  push:
    branch: ["main"]

jobs:
  deploy_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.USERNAME_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Docker Build and Push Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.USERNAME_DOCKER_HUB }}/api_payment:v1.${{ github.run_number }}
          ${{ secrets.USERNAME_DOCKER_HUB }}/api_payment:latest